services:
  web-app:
    build: ./web-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env
  ml-client:
    build: ./machine-learning-client
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
    